- id: letsencrypt_renewal
  alias: Lets encrypt renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: '1635711531127'
  alias: Forward SMS
  description: ''
  trigger:
  - platform: event
    event_type: sms.incoming_sms
  condition: []
  action:
  - service: script.notify_sms_oscar
    data:
      message: 'From: {{trigger.event.data.phone}}

        {{trigger.event.data.text}}

        '
  mode: single
- id: '1648753452907'
  alias: Reboot every Sunday
  description: ''
  trigger:
  - platform: time
    at: 04:45:00
  condition:
  - condition: time
    before: 00:00:00
    weekday:
    - sun
  action:
  - data:
      message: Reboot
    service: notify.sms_oscar
  - service: hassio.host_reboot
    data: {}
  mode: single
- id: '1679363665451'
  alias: Open Pool Valve when Main Tank is full
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.main_tank_water_level
    above: 95
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.pool_water_supply
  mode: single
- id: '1679364103684'
  alias: Close Pool Valve when Main Tank is low
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.main_tank_water_level
    below: 90
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.pool_water_supply
  mode: single
- id: '1679529808488'
  alias: Turn pantry lights on when door opens
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.pantry_door_sensor_window_door_is_open
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.pantry_lights
  mode: single
- id: '1679529882466'
  alias: Turn pantry lights off when door closes
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.pantry_door_sensor_window_door_is_open
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.pantry_lights
  mode: single
- id: '1681787559667'
  alias: Motion Sensor Inactivity Master Bedroom
  description: ''
  use_blueprint:
    path: Oscar_Calvo/motion-sensor-inactivity-automation.yaml
    input:
      motion_sensor_entities:
      - binary_sensor.master_bedroom_sensor_motion_detection
      light_entities:
      - light.master_bedroom_east_light
      - light.master_bedroom_west_light
      - light.master_bedroom_valance_white
      - light.master_bedroom_lights
      climate_entity: climate.master_bedroom
      sun_condition: ignore
- id: '1681787701102'
  alias: Motion Sensor Inactivity Den
  description: ''
  use_blueprint:
    path: Oscar_Calvo/motion-sensor-inactivity-automation.yaml
    input:
      motion_sensor_entities:
      - binary_sensor.den_sensor_motion_detection
      cover_entity: cover.den_blinds
      light_entities:
      - light.den_north_lights
      - light.den_south_lights
      climate_entity: climate.den
      sun_condition: ignore
