- id: letsencrypt_renewal
  alias: Lets encrypt renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: '1635711531127'
  alias: Forward SMS
  description: ''
  trigger:
  - platform: event
    event_type: sms.incoming_sms
  condition: []
  action:
  - service: notify.sms_oscar
    data:
      message: 'From: {{trigger.event.data.phone}}

        {{trigger.event.data.text}}

        '
  mode: single
