- id: letsencrypt_renewal
  alias: Lets encrypt renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: '1635711531127'
  alias: Forward SMS
  description: ''
  trigger:
  - platform: event
    event_type: sms.incoming_sms
  condition: []
  action:
  - service: script.notify_sms_oscar
    data:
      message: 'From: {{trigger.event.data.phone}}

        {{trigger.event.data.text}}

        '
  mode: single
- id: '1648753452907'
  alias: Reboot every Sunday
  description: ''
  trigger:
  - platform: time
    at: 04:45:00
  condition:
  - condition: time
    before: 00:00:00
    weekday:
    - sun
  action:
  - data:
      message: Reboot
    service: notify.sms_oscar
  - service: hassio.host_reboot
    data: {}
  mode: single
- id: '1679363665451'
  alias: Open Pool Valve when Main Tank is full
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.main_tank_water_level
    above: 93
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.pool_water_supply
  mode: single
- id: '1679364103684'
  alias: Close Pool Valve when Main Tank is low
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.main_tank_water_level
    below: 90
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.pool_water_supply
  mode: single
- id: '1679529808488'
  alias: Turn pantry lights on when door opens
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.pantry_door_sensor_window_door_is_open
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.pantry_lights
  mode: single
- id: '1679529882466'
  alias: Turn pantry lights off when door closes
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.pantry_door_sensor_window_door_is_open
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.pantry_lights
  mode: single
- id: '1681787559667'
  alias: Motion Sensor Inactivity Master Bedroom
  description: ''
  use_blueprint:
    path: Oscar_Calvo/motion-sensor-inactivity-automation.yaml
    input:
      motion_sensor_entities:
      - binary_sensor.master_bedroom_sensor_motion_detection
      light_entities:
      - light.master_bedroom_east_light
      - light.master_bedroom_west_light
      - light.master_bedroom_valance_white
      - light.master_bedroom_lights
      climate_entity: climate.master_bedroom
      sun_condition: above_horizon
- id: '1681787701102'
  alias: Motion Sensor Inactivity Den
  description: ''
  use_blueprint:
    path: Oscar_Calvo/motion-sensor-inactivity-automation.yaml
    input:
      motion_sensor_entities:
      - binary_sensor.den_sensor_motion_detection
      cover_entity: cover.den_blinds
      light_entities:
      - light.den_north_lights
      - light.den_south_lights
      climate_entity: climate.den
      sun_condition: ignore
- id: '1682191177071'
  alias: Zwave - Ping Dead Nodes
  description: Try to ping a node if it goes dead to bring it back up
  trigger:
  - platform: event
    event_type: state_changed
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ trigger.event.data.new_state.domain == "sensor" }}'
    - condition: template
      value_template: '{{ trigger.event.data.new_state.state == "dead" }}'
  action:
  - repeat:
      until:
      - condition: template
        value_template: '{{ trigger.event.data.new_state.state == "alive" }}'
      sequence:
      - service: zwave_js.ping
        target:
          entity_id: '{{ trigger.entity_id }}'
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
  mode: parallel
  max: 5
- id: '1682233979057'
  alias: Master Bedroom Lights Double Taps
  description: ''
  use_blueprint:
    path: kpine/ge_double.yaml
    input:
      device: 736aad908eff817b14f1e1d2b34e8837
      double_tap_on:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.master_bedroom_valance_white
      double_tap_off:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.master_bedroom_valance_white
- id: '1683657299093'
  alias: Master Bedroom East Blinds
  description: ''
  use_blueprint:
    path: kpine/ge_double.yaml
    input:
      device: 01cfafa677dc86ae136498ae90736d93
      double_tap_on:
      - service: cover.open_cover
        data: {}
        target:
          entity_id: cover.master_bedroom_blinds
      double_tap_off:
      - service: cover.close_cover
        data: {}
        target:
          entity_id: cover.master_bedroom_blinds
- id: '1683657994954'
  alias: Master Bedroom West Blinds
  description: ''
  use_blueprint:
    path: kpine/ge_double.yaml
    input:
      device: 993e2b576c369a49c4185024ebf75b6c
      double_tap_on:
      - service: cover.open_cover
        data: {}
        target:
          entity_id: cover.master_bedroom_blinds
      double_tap_off:
      - service: cover.close_cover
        data: {}
        target:
          entity_id: cover.master_bedroom_blinds
- id: '1683676341841'
  alias: South Bedroom Blinds
  description: ''
  use_blueprint:
    path: kpine/ge_double.yaml
    input:
      double_tap_on:
      - service: cover.open_cover
        data: {}
        target:
          entity_id: cover.south_bedroom_blinds
      double_tap_off:
      - service: cover.close_cover
        data: {}
        target:
          entity_id: cover.south_bedroom_blinds
      device: 80a3e9cf2f466d5c6c8da4959fec5b4e
- id: '1685075877837'
  alias: Guest Bedroom Blinds
  description: ''
  use_blueprint:
    path: kpine/ge_double.yaml
    input:
      device: d90440495859223e336a7cb88051d00c
      double_tap_on:
      - service: cover.open_cover
        data: {}
        target:
          entity_id: cover.guest_bedroom_blinds
      double_tap_off:
      - service: cover.close_cover
        data: {}
        target:
          entity_id: cover.guest_bedroom_blinds
- id: '1688566072264'
  alias: Master Bedroom Cover opens
  description: ''
  trigger:
  - platform: state
    entity_id:
    - cover.master_bedroom_blinds
    to: opening
  condition: []
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id:
      - cover.master_bedroom_east_blinds_cover
      - cover.master_bedroom_west_blinds_cover
  mode: single
- id: '1703184872764'
  alias: Master Bedroom Blinds Mirror to West-East
  description: ''
  trigger:
  - platform: state
    entity_id:
    - cover.master_bedroom_blinds
    attribute: current_position
  condition: []
  action:
  - service: cover.set_cover_position
    data:
      position: '{{ state_attr(''cover.master_bedroom_blinds'', ''current_position'')
        }}'
    target:
      entity_id:
      - cover.master_bedroom_east_blinds_cover
      - cover.master_bedroom_west_blinds_cover
  mode: single
- id: '1703187404595'
  alias: Motion blinds polling automation
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /30
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: cover.master_bedroom_blinds
  mode: single
- id: '1703725626703'
  alias: Turn on south driveway lights on camera detection
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.south_east_person_detected
      - binary_sensor.south_east_vehicle_detected
      light_switch:
        entity_id:
        - switch.driveway_east_lights
        - light.driveway_south_lights
      include_sun: sun_enabled
      include_night_lights: night_lights_enabled
- id: '1703809610546'
  alias: Mirror Pool Privacy to Pool Cameras Privacy
  description: Mirror Pool Privacy to Pool Cameras Privacy
  trigger:
  - platform: state
    entity_id: switch.pool_privacy
  condition: []
  action:
  - service: switch.turn_{{ trigger.to_state.state }}
    entity_id:
    - switch.south_east_privacy_mode
    - switch.south_west_privacy_mode
    - switch.terrace_north_privacy_mode
    - switch.terrace_south_privacy_mode
    - switch.north_west_privacy_mode
    - switch.west_side_privacy_mode
  mode: single
- id: '1703810407568'
  alias: Turn off pool privacy at 6 AM
  description: Turn off pool privacy at 6 AM
  trigger:
    platform: time
    at: 06:00:00
  action:
    service: switch.turn_off
    entity_id: switch.pool_privacy
  mode: single
- id: '1703974346853'
  alias: Turn Pool Pump if Person detected
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.south_west_person_detected
      light_switch:
        entity_id: switch.pool_waterfall
      time_delay: 15
      after_time: '16:05:00'
      before_time: 09:30:00
      motion_bypass_lights_on:
      - switch.pool_pentair_pump
