- id: letsencrypt_renewal
  alias: Lets encrypt renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: '1635711531127'
  alias: Forward SMS
  description: ''
  trigger:
  - platform: event
    event_type: sms.incoming_sms
  condition: []
  action:
  - service: script.notify_sms_oscar
    data:
      message: 'From: {{trigger.event.data.phone}}

        {{trigger.event.data.text}}

        '
  mode: single
- id: '1648753452907'
  alias: Reboot every Sunday
  description: ''
  trigger:
  - platform: time
    at: 04:45:00
  condition:
  - condition: time
    before: 00:00:00
    weekday:
    - sun
  action:
  - data:
      message: Reboot
    service: notify.sms_oscar
  - service: hassio.host_reboot
    data: {}
  mode: single
- id: '1679363665451'
  alias: Open Pool Valve when Main Tank is full
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.main_tank_water_level
    above: 95
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.pool_water_supply
  mode: single
- id: '1679364103684'
  alias: Close Pool Valve when Main Tank is low
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.main_tank_water_level
    below: 90
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.pool_water_supply
  mode: single
