#- platform: ping
#  host: 192.168.10.73
#  scan_interval: 30
#  count: 3
#  name: Main Water Tank Connection
#- platform: ping
#  host: 192.168.10.219
#  scan_interval: 30
#  count: 3
#  name: Secondary Water Tank Connection
- platform: template
  sensors:
    power_outage:
      friendly_name: "Power Outage"
      device_class: power
      value_template: "{{ (states('sensor.solaredge_m2_ac_current') == 'unknown') and (states('sensor.solaredge_i1_ac_current') != 'unknown') and (states('sensor.solaredge_i2_ac_current') != 'unknown') }}"
