- platform: template
  sensors:
    power_outage:
      friendly_name: "Power Outage"
      device_class: power
      value_template: "{{ (states('sensor.solaredge_m2_ac_current') == 'unknown') and (states('sensor.solaredge_i1_ac_current') != 'unknown') and (states('sensor.solaredge_i2_ac_current') != 'unknown') }}"
