
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

#sms:
#  device: /dev/ttyUSB0

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notify.yaml
sensor: !include sensors.yaml
template: !include templates.yaml
python_script:
conversation:

climate:
  - platform: ccm15
    name: mideaccm
    host: ac-controller.cr.calvonet.com
    port: 80
    scan_interval: 10

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

logger:
  default: info
  logs:
    homeassistant.components.sms: debug
    gammu: debug
