
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

#sms:
#  device: /dev/ttyUSB0

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
notify: !include notify.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
template: !include templates.yaml
alert: !include alerts.yaml
python_script:
conversation:

climate: !include climate.yaml
mqtt: !include mqtt.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

alarm_control_panel:
  - platform: manual
    name: Home Alarm

#logger:
#  default: info
#  logs:
#    homeassistant.components.sms: debug
#    gammu: debug
