- platform: group
  name: sms_oscar
  services:
    - service: sms
      data:
        target: !secret sms_oscar
- platform: group
  name: sms_hazel
  services:
    - service: sms
      data:
        target: !secret sms_hazel
