- platform: rest
  name: sms
  resource: !secret sms_gateway
  method: POST_JSON
  authentication: basic
  username: !secret sms_gateway_user
  password: !secret sms_gateway_password
  target_param_name: number
  message_param_name: text
- platform: group
  name: sms_oscar
  services:
    - service: sms
      data:
        target: !secret sms_oscar
- platform: group
  name: sms_hazel
  services:
    - service: sms
      data:
        target: !secret sms_hazel
- platform: group
  name: critical
  services:
    - service: sms_oscar
    - service: mobile_app_oscar_phone
    - service: sms_hazel
    - service: mobile_app_hazel_phone
