- platform: rest
  name: Aboveground Water Tank Pressure
  resource: http://192.168.10.73/get_sensors
  scan_interval: 30
  timeout: 80
  value_template: >
    {{ (value_json.local_s | regex_findall_index("1\":(-?\d+\.?\d+)") | float) | round(0) }}
  availability: >
    {{ states('binary_sensor.main_water_tank_connection')|bool }}
  unit_of_measurement: "hPa"
- platform: rest
  name: Underground Water Tank Pressure
  resource: http://192.168.10.219/get_sensors
  scan_interval: 30
  timeout: 80
  value_template: >
    {{ (value_json.local_s | regex_findall_index("1\":(-?\d+\.?\d+)") | float) | round(0) }}
  unit_of_measurement: "hPa"
- platform: statistics
  name: Main Tank Water Level Sensor Distance Max
  entity_id: sensor.main_tank_water_level_sensor_distance
  state_characteristic: value_max
  #sampling_size: 20
  max_age:
    minutes: 45
- platform: template
  sensors:
    failed_zwave:
      value_template: >
        {{ states | selectattr("entity_id", "search", "node_status") |
           selectattr('state', 'in', 'dead, unavailable, unknown') |
           map(attribute='entity_id') | list }}
