esphome:
  name: central-bedrrom-panel
  friendly_name: Central Bedrrom Panel

# Replace this with your actual platform if you aren't using ESP32.
esp32:
  board: esp32dev

logger:

api:
  encryption:
    key: "i6mILZD17XvOYOEZanJVJy/Sf9XnMZARZ3A/Dw+gZHM="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Central Bedrrom Fallback Hotspot
    password: "K0rfhZv3PFzp"

captive_portal:
